# Generated by Django 5.0.6 on 2024-06-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_sach', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ctphieuhuys',
            fields=[
                ('id_ctphieuhuy', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ctphieuhuys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ctphieunhaps',
            fields=[
                ('id_ctphieunhap', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ctphieunhaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docgias',
            fields=[
                ('id_docgia', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('birthday', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('ngay_tao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'docgias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieuhuys',
            fields=[
                ('id_phieuhuy', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ngay_huy', models.CharField(max_length=50)),
                ('ly_do_huy', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phieuhuys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieumuons',
            fields=[
                ('id_phieumuon', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ngay_tao', models.CharField(max_length=50)),
                ('ngay_hen_tra', models.CharField(max_length=50)),
                ('trang_thai', models.IntegerField()),
                ('ngay_tra', models.CharField(max_length=50)),
                ('ghi_chu', models.CharField(max_length=255)),
                ('so_luong', models.IntegerField()),
            ],
            options={
                'db_table': 'phieumuons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phieunhaps',
            fields=[
                ('id_phieunhap', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('donvi_cungcap', models.CharField(max_length=255)),
                ('ngay_nhap', models.CharField(max_length=50)),
                ('ly_do_nhap', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'phieunhaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thethuviens',
            fields=[
                ('id_the', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('ngay_tao', models.CharField(max_length=50)),
                ('ngay_het_han', models.CharField(max_length=50)),
                ('ghi_chu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'thethuviens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('birthday', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
