# Generated by Django 5.0.6 on 2024-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctkiemkes',
            fields=[
                ('id_ctkiemke', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('so_luong_kiemke', models.IntegerField()),
                ('so_luong_bandau', models.IntegerField()),
            ],
            options={
                'db_table': 'ctkiemkes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kiemkes',
            fields=[
                ('id_kiemke', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ngay_tao', models.CharField(max_length=50)),
                ('ly_do', models.CharField(max_length=255)),
                ('file_kiemke', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kiemkes',
                'managed': False,
            },
        ),
    ]
